language: cpp
dist: trusty
os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    # YARP and KDL
    - libeigen3-dev

    # OpenRAVE
    - libboost-all-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev

    # ROBOTICSLAB
    - libopencv-dev
    - libspnav-dev

before_install:
  #-- Add source repository for PCL-related packages
  - sudo add-apt-repository --yes ppa:v-launchpad-jochen-sprickerhof-de/pcl
  - sudo apt-get -qq update

install:
  #-- Install PCL
  - sudo apt-get install libpcl-all-dev

  #-- Install ROBOTICSLAB deps
  - sudo apt-get install libxwiimote-dev

before_script:
  - mkdir -p build && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install-system" -DNON_INTERACTIVE_BUILD=ON

script:
  - make install

after_success:
  - make uninstall
